before_script: cd website
language: node_js
node_js:
  - '10'
branches:
  only:
    - master
cache:
  yarn: true
addons:
sonarcloud:
  organization: xyo-network
install:
- yarn install
script:
- yarn build
- sonar-scanner