before_script: cd website
language: node_js
node_js:
  - '10'
cache:
  directories:
    - node_modules
addons:
  sonarcloud:
    organization: xyo-network
branches:
  only:
    - master
cache:
  yarn: true
script:
- yarn run build
- sonar-scanner